# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingNeighborhood',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('school', models.IntegerField()),
                ('income', models.IntegerField()),
                ('cta', models.IntegerField()),
            ],
        ),
    ]
