# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_testingneighborhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingNeighborhood',
        ),
    ]
